NumPy，全称Numerical Python，是Python科学计算的基础包²。它是一个Python库，提供多维数组对象，各种派生对象（如掩码数组和矩阵），以及用于数组快速操作的各种API，有包括数学、逻辑、形状操作、排序、选择、输入输出、离散傅立叶变换、基本线性代数，基本统计运算和随机模拟等等²。

NumPy的核心是ndarray对象。这个对象封装了同数据类型的n维数组。许多操作都是在代码本地进行编译后执行的，以保证其性能优良²。NumPy数组在创建时具有固定的大小，与Python的原生数组对象（可以动态增长）不同。更改ndarray的大小将创建一个新数组并删除原来的数组²。

以下是一些NumPy的使用实例⁵：

1. 创建一个长度为10的零向量：

In [2]:
import numpy as np
Z = np.zeros(10)
print(Z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
import numpy as np
# 创建一个10*10的值为0的二维数组
Z = np.zeros((10, 10),dtype=bool)
print(Z)


[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


2. 计算每一列的总和：


In [9]:
# 创建一个 3x3 的 NumPy 数组
Z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Z)
print("--------")
# 使用 `np.sum()` 函数沿着列求和
print(np.sum(Z, axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------
[12 15 18]


参数

Z : 要求和的数组
axis : 求和的轴，0 表示沿着行求和，1 表示沿着列求和
返回值

一个新数组，其中包含沿着指定轴求和的结果
解释

该代码首先创建一个 3x3 的 NumPy 数组 Z。
然后使用 np.sum() 函数沿着行求和 Z。
由于 axis 为 0，因此 np.sum() 函数将 Z 的每一列求和，并将结果返回为一个新数组。

np.sum(Z, axis=0)会沿着列（axis=0）方向对数组进行求和操作。
想沿着行方向求和，可以使用np.sum(Z, axis=1)。
想对整个数组求和，可以使用np.sum(Z)

In [14]:
# 创建一个 3x3 的 NumPy 数组
Z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(Z)
# 使用 `np.sum()` 函数沿着行求和
print(np.sum(Z, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


3. 将所有大于30的元素替换为0：

In [15]:
the_array = np.array([49, 7, 44, 27, 13, 35, 71])
an_array = np.where(the_array > 30, 0, the_array)
print(an_array)

[ 0 -1  0 -1 -1  0  0]


4. 将一维数组重塑为一列的二维数组：

In [21]:
Z = np.arange(8)
print(Z)
Z = Z.reshape(-1,4)
print(Z)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


以上只是NumPy库中功能的一部分，实际上NumPy有许多其他强大且有用的功能供你选择和使用。

源: 与必应的对话， 2023/9/10
(1) NumPy 介绍 | NumPy. https://www.numpy.org.cn/user/setting-up.html.
(2) 90个NumPy案例，建议收藏！ - 知乎 - 知乎专栏. https://zhuanlan.zhihu.com/p/457284372.
(3) NumPy 教程 | 菜鸟教程. https://www.runoob.com/numpy/numpy-tutorial.html.
(4) 全网最全的Numpy开发入门教程（详细案例版） - CSDN博客. https://blog.csdn.net/sinat_28371057/article/details/113813753.
(5) Python科学计算和数据分析（NumPy详细介绍） - 知乎. https://zhuanlan.zhihu.com/p/337456511.
(6) Numpy的使用(超详细，有代码示例) - CSDN博客. https://blog.csdn.net/VariatioZbw/article/details/104765365.
(7) 这100个小案例，带你玩转 Numpy！ - 知乎 - 知乎专栏. https://zhuanlan.zhihu.com/p/402452690.
(8) undefined. http://www.numpy.org/.
(9) undefined. https://github.com/numpy/numpy.
(10) undefined. https://www.scipy.org/.
(11) undefined. https://github.com/scipy/scipy.
(12) undefined. https://matplotlib.org/.
(13) undefined. https://github.com/matplotlib/matplotlib.

NumPy库中有许多其他有用的函数，以下是一些例子：

1. **add()**：此函数用于数组元素的加法运算²。
2. **subtract()**：此函数用于数组元素的减法运算²。
3. **multiply()**：此函数用于数组元素的乘法运算²。
4. **divide()**：此函数用于数组元素的除法运算²。
5. **power()**：此函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂²。
6. **mod()**或**remainder()**：这两个函数都用于计算输入数组中相应元素相除后的余数²。
7. **reciprocal()**：此函数返回参数逐元素的倒数²。

以上只是NumPy库中功能的一部分，实际上NumPy有许多其他强大且有用的功能供你选择和使用。你可以根据你的具体需求来选择合适的函数。¹

源: 与必应的对话， 2023/9/10
(1) NumPy 算术函数 | 菜鸟教程. https://www.runoob.com/numpy/numpy-arithmetic-operations.html.
(2) NumPy 教程 | 菜鸟教程. https://www.runoob.com/numpy/numpy-tutorial.html.
(3) 50个常用的 Numpy 函数详解！ - 知乎 - 知乎专栏. https://zhuanlan.zhihu.com/p/562082459.
(4) undefined. http://www.numpy.org/.
(5) undefined. https://github.com/numpy/numpy.
(6) undefined. https://www.scipy.org/.
(7) undefined. https://github.com/scipy/scipy.
(8) undefined. https://matplotlib.org/.
(9) undefined. https://github.com/matplotlib/matplotlib.

在NumPy中，`multiply()`和`dot()`两个函数的作用不同。`multiply()`函数用于对应位置元素相乘（点乘），而`dot()`函数用于矩阵乘法¹。

例如，假设我们有两个矩阵a和v：
```python
import numpy as np
a = np.matrix([[1,2], [4,5]])
v = np.matrix([[7], [8]])
```
使用`multiply()`函数进行点乘：
```python
d = np.multiply(a,v)
print(d)
```
输出结果为：
```
[[ 7 14]
 [32 40]]
```
使用`dot()`函数进行矩阵乘法：
```python
c = np.dot(a,v)
print(c)
```
输出结果为：
```
[[23]
 [68]]
```
需要注意的是，运算符重载“*”、“@”并不完全等于`dot()`、`multiply()`，在不同类型之间的行为有所区别¹。例如，在matrix之间使用“*”时，优先执行矩阵乘法，使用`multiply()`则始终先广播后对位相乘¹。因此，在使用这些函数时，需要注意数据类型和运算符的选择。

源: 与必应的对话， 2023/9/10
(1) Python NumPy中 dot() / multiply() / @ / * 之间的区别 - 知乎. https://zhuanlan.zhihu.com/p/480960607.
(2) Numpy数据的操作 * dot() multiply() 的区别 - 我是小随 - 博客园. https://www.cnblogs.com/AlvinSui/p/8733470.html.
(3) numpy中dot()、outer()、multiply()以及matmul()的区别 - 简书. https://www.jianshu.com/p/42b0b6ffcf97.

`multiply()` 和 `dot()` 是两个不同的数学操作，通常用于处理向量和矩阵。

1. **`multiply()`：**
   - `multiply()` 是一个元素级别的操作，用于对两个数组（可以是向量、矩阵或多维数组）中的对应元素进行相乘。它会将两个输入数组中相同位置的元素相乘，生成一个具有相同形状的输出数组。
   - 这意味着 `multiply()` 不执行矩阵乘法（矩阵的点积），而只是执行逐元素的乘法。这对于执行逐元素操作（如元素级别的乘法、加法等）很有用。

   例如，在Python中使用NumPy库，您可以执行以下操作：

   ```python
   import numpy as np

   a = np.array([1, 2, 3])
   b = np.array([4, 5, 6])
   result = np.multiply(a, b)
   # 结果是 [4, 10, 18]
   ```

2. **`dot()`：**
   - `dot()` 是矩阵的点积或向量的内积运算。对于两个一维数组，它计算它们的内积（数量积）。对于两个多维数组（矩阵），它执行矩阵乘法，返回一个新的矩阵。
   - 矩阵乘法是一种线性代数运算，它涉及到将一个矩阵的行与另一个矩阵的列相乘，并将结果累加起来以生成新的矩阵。

   例如，在Python中使用NumPy库，您可以执行以下操作：

   ```python
   import numpy as np

   A = np.array([[1, 2], [3, 4]])
   B = np.array([[5, 6], [7, 8]])
   result = np.dot(A, B)
   # 结果是 [[19, 22], [43, 50]]
   ```

总之，`multiply()` 和 `dot()` 用于不同的数学操作。`multiply()` 执行逐元素的乘法，而 `dot()` 执行矩阵乘法或向量的内积运算，具体取决于输入的数组的维度和形状。

In [22]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.multiply(a, b)
# 结果是 [4, 10, 18]
result

array([ 4, 10, 18])

In [23]:
import numpy as np

a = np.array([[1, 2, 3],[1, 2, 3]])
print(a)
b = np.array([[3, 2, 1],[4, 5, 6]])
print(b)
result = np.multiply(a, b)
# 结果是 [4, 10, 18]
print(result)

[[1 2 3]
 [1 2 3]]
[[3 2 1]
 [4 5 6]]
[[ 3  4  3]
 [ 4 10 18]]


In [24]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
# 结果是 [[19, 22], [43, 50]]
result

array([[19, 22],
       [43, 50]])

In [26]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.multiply(A, B)
print(result)
# 应输出：
# [[19 22]
#  [43 50]]


[[ 5 12]
 [21 32]]


In [27]:
import numpy as np

def find_closest_values(arr, target):
    # 对数组中的元素与目标值的差值进行排序
    sorted_indices = np.argsort(np.abs(arr - target))
    
    # 返回距离最小的两个元素
    closest_indices = sorted_indices[:2]
    closest_values = arr[closest_indices]
    
    return tuple(closest_values)

arr = np.array([1, 3, 5, 7, 8, 12, 15])
target = 9
result = find_closest_values(arr, target)
print(result)


(8, 7, 12)


NumPy中的随机函数常常用于按照某种概率统计规则来产生随机数，在机器学习和深度学习中，我们常常需要使用随机函数对一些参数进行初始化¹。以下是一些NumPy中常用的随机函数：

1. **random.rand(d0, d1, ..., dn)**：产生 [0, 1)范围的浮点随机数。rand函数用于产生 [0, 1)范围内的浮点随机数，其中参数dn表示第n个维度的长度¹。

```python
import numpy as np
# 产生shape为 (d0, d1,..., dn), 值为 [0, 1) 范围内的浮点随机数
# 默认d0 = 1, 产生 [0, 1)范围内的一个浮点随机数
a = np.random.rand()
# d0 = 2, 产生 [0, 1)范围内的一维数组（向量）的浮点随机数
b = np.random.rand(2)
# d0 = 2, d1 = 3, 产生 [0, 1)范围内的二维数组（矩阵）的浮点随机数
c = np.random.rand(2,3)
print(a)
print(b)
print(c)
```

2. **random.random_sample(size)**：产生 [0, 1)范围内的浮点随机数。random_sample函数用于产生 [0, 1)范围的浮点随机数，其中参数size为产生数组的大小，如果不指定则会产生一个随机数¹。

```python
import numpy as np
# 产生shape为size, 值为 [0, 1) 范围内的浮点随机数
# 不指定size参数, 产生 [0, 1)范围内的浮点随机数
a = np.random.random_sample()
# 指定size参数,产生 [0, 1)范围内的二维数组（矩阵）的浮点随机数​
b = np.random.random_sample(size = (2, 3))
print(a)
print(b)
```

3. **random.randint(low, high=None, size=None)**：产生 [low, high)范围内的整型随机数。random.randint随机函数用于产生 [low, high)范围的随机整数，需要注意范围是"包左不包右"，包含low但是不包含high。size为产生数组的大小¹。

```python
import numpy as np
# 产生shape为size, 值为 [low, high) 范围内的整型随机数
# low = 0, high = 3, 产生 [0, 3)范围内的一个整型随机数
a = np.random.randint(0, 3)
# low = 3, 产生 [0, 3)范围内的一维数组（向量）的整型随机数
b = np.random.randint(3, size = 4)
# low = 0, high = 3, 产生 [0, 3)范围内的二维数组（矩阵）的整型随机数
c = np.random.randint(0, 3, size = (2, 3))
print(a)
print(b)
print(c)
```

以上只是NumPy库中功能的一部分，实际上NumPy有许多其他强大且有用的功能供你选择和使用。你可以根据你的具体需求来选择合适的函数¹。

源: 与必应的对话， 2023/9/10
(1) Numpy中常用随机函数的总结 - 知乎 - 知乎专栏. https://zhuanlan.zhihu.com/p/146021617.
(2) numpy.random.rand — NumPy v1.25 Manual. https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html.
(3) Numpy的随机函数_shmilyam的博客-CSDN博客. https://blog.csdn.net/shmilyam/article/details/105902561.
(4) numpy中生成随机数的几种常用函数 - 华为云社区. https://bbs.huaweicloud.com/blogs/267789.

In [28]:
import numpy as np
# 产生shape为 (d0, d1,..., dn), 值为 [0, 1) 范围内的浮点随机数
# 默认d0 = 1, 产生 [0, 1)范围内的一个浮点随机数
a = np.random.rand()
# d0 = 2, 产生 [0, 1)范围内的一维数组（向量）的浮点随机数
b = np.random.rand(2)
# d0 = 2, d1 = 3, 产生 [0, 1)范围内的二维数组（矩阵）的浮点随机数
c = np.random.rand(2,3,3)
print(a)
print(b)
print(c)

0.9825015446705124
[0.56914325 0.09995357]
[[[0.42457578 0.19114038 0.83703472]
  [0.3867655  0.05576654 0.94529947]
  [0.58172593 0.68561758 0.61086025]]

 [[0.80724834 0.18841389 0.97147661]
  [0.01446803 0.25764995 0.68310819]
  [0.55492852 0.77484206 0.51943727]]]


In [23]:
import numpy as np
# 产生shape为size, 值为 [0, 1) 范围内的浮点随机数
# 不指定size参数, 产生 [0, 1)范围内的浮点随机数
a = np.random.random_sample()
# 指定size参数,产生 [0, 1)范围内的二维数组（矩阵）的浮点随机数​
b = np.random.random_sample(size = (2, 3))
print(a)
print(b)

0.9237377905835453
[[0.58626397 0.22042523 0.17689784]
 [0.56759178 0.78923237 0.22995826]]


In [24]:
import numpy as np
# 产生shape为size, 值为 [low, high) 范围内的整型随机数
# low = 0, high = 3, 产生 [0, 3)范围内的一个整型随机数
a = np.random.randint(0, 3)
# low = 3, 产生 [0, 3)范围内的一维数组（向量）的整型随机数
b = np.random.randint(3, size = 4)
# low = 0, high = 3, 产生 [0, 3)范围内的二维数组（矩阵）的整型随机数
c = np.random.randint(0, 3, size = (2, 3))
print(a)
print(b)
print(c)

2
[0 1 0 1]
[[1 2 1]
 [0 1 1]]


In [31]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\xyt55\AppData\Local\Temp\ipykernel_24028\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\xyt55\AppData\Local\Temp\ipykernel_24028\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\xyt55\AppData\Local\Temp\ipykernel_24028\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


`df.drop()` 是Pandas中用于删除DataFrame中行或列的函数。它允许您根据标签或索引删除指定的行或列，同时可以选择是否在原始DataFrame上执行删除操作（默认情况下不会在原地执行，除非设置了`inplace=True`参数）。

以下是 `df.drop()` 函数的主要参数和用法：

```python
df.drop(labels, axis=0, index=None, columns=None, inplace=False)
```

- `labels`：要删除的行或列的标签（可以是单个标签或标签列表）。
- `axis`：指定删除的轴，可以是0（默认）表示删除行，或1 表示删除列。
- `index`：可选参数，与`labels`相同，用于删除行。
- `columns`：可选参数，与`labels`相同，用于删除列。
- `inplace`：可选参数，如果设置为True，将在原始DataFrame上执行删除操作，而不是返回一个新的DataFrame。默认为False。

示例：

```python
import pandas as pd

data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}
df = pd.DataFrame(data)

# 删除一行（使用标签）
df = df.drop(0)  # 删除第一行
# 或者
df = df.drop(index=0)

# 删除一列（使用标签）
df = df.drop('B', axis=1)  # 删除列 'B'
# 或者
df = df.drop(columns='B')

# 在原地执行删除操作
df.drop(0, inplace=True)  # 删除第一行，并在原地执行删除
df.drop('B', axis=1, inplace=True)  # 删除列 'B'，并在原地执行删除
```

请注意，`df.drop()` 默认情况下不会更改原始DataFrame，而是返回一个新的DataFrame。如果要在原地执行删除操作，可以将`inplace`参数设置为True。

`inplace` 参数用于指示是否在原始DataFrame上执行操作。它是一个布尔值，如果设置为True，将在原地（原始DataFrame上）执行操作，如果设置为False（默认值），则返回一个新的DataFrame，而不更改原始DataFrame。

具体来说，`inplace=True` 的作用是在原始DataFrame上执行操作，并将结果直接修改原始DataFrame。这意味着原始DataFrame将被更改，不会返回一个新的DataFrame。使用 `inplace=True` 可以节省内存，因为不需要为结果创建一个新的DataFrame，但请谨慎使用，因为操作是不可逆的，可能会导致数据丢失。

例如，如果您有一个名为`df`的DataFrame，并希望删除其中的一列，您可以使用 `inplace=True` 来在原地执行删除操作：

```python
df.drop('Column_Name', axis=1, inplace=True)
```

如果将 `inplace` 设置为False或不指定，删除操作将返回一个新的DataFrame，并且原始的`df`将保持不变：

```python
new_df = df.drop('Column_Name', axis=1)  # 原始的 df 不受影响
```

总之，`inplace` 参数的作用是控制是否在原始DataFrame上执行操作，以及是否返回一个新的DataFrame。根据需求选择合适的设置。如果不确定，建议首先创建一个新的DataFrame，以免意外更改原始数据。