### In this notebook we are going to discuss a vast majority of the NumPy Library using numerous Examples

<div>
<img src="https://numpy.org/images/logos/numpy.svg" width="250"/>
</div>

# What is NumPy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.


## Why is Numpy Fast?
Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

* vectorized code is more concise and easier to read
* fewer lines of code generally means fewer bugs
* the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)
* vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. Moreover, in the example above, a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the smaller array is “expandable” to the shape of the larger in such a way that the resulting broadcast is unambiguous.

# <a id='main'>Table of Contents</a>
- [NumPy Arrays : Creating Arrays](#NA)
- [Slicing and Indexes](#S&I)
- [Reshaping Arrays](#RA)
- [Stacking & Splitting](#S&S)
- [Copying](#C)
- [Basic Math](#BM)
- [Reading from Files](#RFF)
- [Statistics Functions](#SF)
- [Trigonometric Functions](#TF)
- [Matrix Functions](#MF)
- [Saving & Loading NumPy Objects](#S&LNO)
- [Financial Functions](#FF)
- [Comparison Functions](#CF)

# <a id='NA'>NumPy Arrays : Creating Arrays</a>
[Go back to the main page](#main)

In [1]:
import numpy as np
# Provide Beautiful plots of numerous type that are either static, animated and/or interactiv
import matplotlib.pylab as plt
from numpy import random

# A python List
list_1 = [1, 2, 3, 4, 5]

# Create NumPy 1 dimensional (a axis) array list object of type byte (-128 to 127)
# A N-dimensional array is a usually fixed size multi dimensional
# array that contains items of the same type.
np_arr_1 = np.array(list_1, dtype = np.int8)
np_arr_1
# Create multidimensional list
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create NumPy multidimensional (2 axis) array without defining type
np_m_arr_1 = np.array(m_list_1)

# you can also create arrays by defining the start value,
# stop value (upto but not include stop) and step amount
np.arange(1, 10)

# With floats define start, end and number of values
np.linspace(0, 5, 4)

# You can Create a 3 item arrays of Zeros
np.zeros(3)

# you can create multidimensional arrays of zeros by passing
# a tuple with th 1st value being rows and the 2nd columns
np.zeros((2, 3))

# Create array of 1s
np.ones((2, 3))

# Create array with defined values
np_arr_2 = np.array([1, 2, 3, 4, 5, 6])

# Get type for array
np_arr_2.dtype

# Data Types
# Boolean : np.bool_
# Char : np.byte
# Short : np.short
# Integer : np.short_
# Long : np.int_
# Float : np.single & np.float32
# Doulbe : np.double & np.float64
# np.int8 : -128 to 127
# np.int16 : -32768 to 32767
# np.int32 : -2147483648 to 2147483647
# np.int64 : -9223372036854775808 to 9223372036854775807

# Create random 5 value 1D array from 10 to 50
np.random.randint(10, 50, 5)
# create random matrix 2x3 with values between 10 and 50
np.random.randint(10, 50, size=(2,3))

# Get help with a function
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.randint`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outpu

# <a id='S&I'>Slicing & Indexes</a>
[Go back to the main page](#main)

In [2]:
# Change value at index
# np_m_arr_1[0, 0] = 2
# np_m_arr_1.itemset((0,1),1)
np_m_arr_1
# Get size and shape of array
np_m_arr_1.shape
np_m_arr_1.size
# Get value by index
np_m_arr_1[0,1]
np_m_arr_1.item(0,1)

# Get specific indices
np.take(np_m_arr_1, [0, 3, 6])
# Replace provided index values with new values
np.put(np_m_arr_1, [0, 3, 6], [10, 10, 10])
print(np_m_arr_1)

# Start at 1st through 5th with 2 step
np_arr_1[:5:2]
# Get 2nd value from each row
np_m_arr_1[:,1]
# Flip array
np_arr_1[::-1]

# Get evens
evens = np_m_arr_1[np_m_arr_1%2==0]
evens

# Get values > 5
np_m_arr_1[np_m_arr_1 > 5]
# 5 < values < 9
np_m_arr_1[(np_m_arr_1 > 5) & (np_m_arr_1 < 9)]
# 5 < values or values = 10
np_m_arr_1[(np_m_arr_1 > 5) | (np_m_arr_1 == 10)]

# Find Uniques
np.unique(np_m_arr_1)

[[10  2  3]
 [10  5  6]
 [10  8  9]]


array([ 2,  3,  5,  6,  8,  9, 10])

# <a id='RA'>Reshaping Arrays</a>
[Go back to the main page](#main)

In [3]:
# Reshape array to 1 by 9
#np_m_arr_1.reshape((1, 9))
np_m_arr_1
# Reshape array to 2 by 5 (Items are either lost or 0 is added)
np_m_arr_1.resize((2,5))
np_m_arr_1
# Transpose axes
np_m_arr_1.transpose()
# Swap axes
np_m_arr_1.swapaxes(0, 1)
# Flatten in order
np_m_arr_1.flatten()
# Flatten in column order
np_m_arr_1.flatten('F')
# Sort rows
np_m_arr_1.sort(axis=1)
print(np_m_arr_1)
# Sort columns
np_m_arr_1.sort(axis=0)
np_m_arr_1

[[ 2  3  5 10 10]
 [ 0  6  8  9 10]]


array([[ 0,  3,  5,  9, 10],
       [ 2,  6,  8, 10, 10]])

# <a id='S&S'>Stacking & Splitting</a>
[Go back to the main page](#main)

In [4]:
# Generate random arrays
ss_arr_1 = np.random.randint(10, size=(2, 2))
print(f"ss_arr_1\n{ss_arr_1}")
ss_arr_2 = np.random.randint(10, size=(2, 2))
print(f"ss_arr_2\n{ss_arr_2}")

# Stack arr_2 under arr_1
np.vstack((ss_arr_1, ss_arr_2))
# Stack horizontally
np.hstack((ss_arr_1, ss_arr_2))

# Delete 2nd row on each array
ss_arr_3 = np.delete(ss_arr_1, 1, 0)
ss_arr_4 = np.delete(ss_arr_2, 1, 0)
print(f"ss_arr_3\n{ss_arr_3}")
print(f"ss_arr_4\n{ss_arr_4}")

# Combine arrays
np.column_stack((ss_arr_3, ss_arr_4))
# Stack in a 2D array
np.row_stack((ss_arr_3, ss_arr_4))

# Generate 2x10 array
ss_arr_5 = np.random.randint(10, size=(2, 10))
print(f"ss_arr_5\n{ss_arr_5}")
# Split into 5 arrays taking from both arrays in multidimensional array
np.hsplit(ss_arr_5, 5)
# Split after 2nd & 4th column
np.hsplit(ss_arr_5, (2, 4))

ss_arr_1
[[5 5]
 [0 6]]
ss_arr_2
[[9 0]
 [0 1]]
ss_arr_3
[[5 5]]
ss_arr_4
[[9 0]]
ss_arr_5
[[5 2 7 0 5 3 6 4 2 4]
 [4 2 5 0 1 4 0 0 8 7]]


[array([[5, 2],
        [4, 2]]),
 array([[7, 0],
        [5, 0]]),
 array([[5, 3, 6, 4, 2, 4],
        [1, 4, 0, 0, 8, 7]])]

# <a id='C'>Copying</a>
[Go back to the main page](#main)

In [5]:
cp_arr_1 = np.random.randint(10, size=(2, 2))
# Both variables point at the same array
cp_arr_2 = cp_arr_1
# Change value
cp_arr_1[0,0] = 2
print(f"cp_arr_1\n{cp_arr_1}")
print(f"cp_arr_2\n{cp_arr_2}")


cp_arr_1
[[2 9]
 [3 6]]
cp_arr_2
[[2 9]
 [3 6]]


# <a id='BM'>Basic Math</a>
[Go back to the main page](#main)

In [6]:
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 4, 6, 8])
# Add Values
arr_3 + arr_4
# Subtract
arr_3 - arr_4
# Multiply
arr_3 * arr_4
# Divide
arr_3 / arr_4
# Random 4 digit 1D array between 0 to 100
arr_5 = random.randint(100, size=(4))
arr_5
# Random 2 by 3 digit 2D array between 0 to 100
arr_6 = random.randint(100, size=(2, 3))
arr_6
# 4 random floats
random.rand(4)
# Get random value from an array
random.choice(arr_3)

# Sum of values in array
arr_3.sum()
# Sum columns
print(arr_6)
arr_6.sum(axis=0)
# Cumulative sum of rows
arr_6.cumsum(axis=1)

# Minimum of each row
arr_6.min(axis=1)
# Maximumof each column
arr_6.max(axis=0)

print(f"arr_3 {arr_3}")
print(f"arr_4 {arr_4}")
# Adding individual numbers to array
np.add(arr_3, 5)
# Add arrays
np.add(arr_3, arr_4)
# Subtract
np.subtract(arr_3, arr_4)
# Multiply
np.multiply(arr_3, arr_4)
# Divide
np.divide(arr_3, arr_4)

arr_5 = np.array([[1, 2], [3, 4]])
arr_6 = np.array([[2, 4], [6, 9]])
print(f"arr_5\n{arr_5}")
print(f"arr_6\n{arr_6}")
# Divides elments in 1st array by 2nd array and returns remainder
np.remainder(arr_6, arr_5)

# Return values in 1st array to powers defined in 2nd array
np.power(arr_6, arr_5)
# Square root
np.sqrt(arr_3)
# Cube root
np.cbrt(arr_3)
# Absolute value of every element
np.absolute([-1, -2])
# Exponential of all element in array
np.exp(arr_3)
# Log functions
np.log(arr_3)
np.log2(arr_3)
np.log10(arr_3)
# Greatest common divisor
np.gcd.reduce([9, 12, 15])
# Lowest common multiple
np.lcm.reduce([9, 12, 15])

# Round down
np.floor([1.2, 2.5])
# Round up
np.ceil([1.2, 2.5])

# can receive 6 values and square them
sq_arr = np.arange(6)**2
sq_arr[arr_3]

arr_7 = random.randint(100, size=(5, 3))
print(f"arr_7\n{arr_7}")
# Get index for max value per column
mc_index = arr_7.argmax(axis=0)
mc_index
# Get numbers corresponding to indexes
max_nums = arr_7[mc_index]
max_nums
arr_7[mc_index, range(arr_7.shape[1])]

[[31 87 55]
 [74 52 56]]
arr_3 [1 2 3 4]
arr_4 [2 4 6 8]
arr_5
[[1 2]
 [3 4]]
arr_6
[[2 4]
 [6 9]]
arr_7
[[87 10  9]
 [18 42 77]
 [47 53 63]
 [ 4 20 34]
 [ 5 36 90]]


array([87, 53, 90])

# <a id='RFF'>Reading from Files</a>
[Go back to the main page](#main)

In [8]:
# Pandas is use to manipulate tabular data and more
import pandas as pd
# Import using Numpy
from numpy import genfromtxt

# Read table of data from CSV file and convert to Numpy array
ic_sales = pd.read_csv('./data/icecreamsales.csv').to_numpy()
ic_sales

# Read data using NumPy
ic_sales_2 = genfromtxt('./data/icecreamsales.csv', delimiter=',')
# Remove NaNs
ic_sales_2 = [row[~np.isnan(row)] for row in ic_sales_2]
ic_sales_2

[array([], dtype=float64),
 array([ 37., 292.]),
 array([ 40., 228.]),
 array([ 49., 324.]),
 array([ 61., 376.]),
 array([ 72., 440.]),
 array([ 79., 496.]),
 array([ 83., 536.]),
 array([ 81., 556.]),
 array([ 75., 496.]),
 array([ 64., 412.]),
 array([ 53., 324.]),
 array([ 40., 320.])]

# <a id='SF'>Statistics Functions</a>
[Go back to the main page](#main)

In [9]:
# Array 1 - 5
sarr_1 = np.arange(1, 6)
np.mean(sarr_1)
np.median(sarr_1)
np.average(sarr_1)
np.std([4, 6, 3, 5, 2]) # Standard Deviation
np.var([4, 6, 3, 5, 2]) # Variance
# Also nanmedian, nanmean, nanstd, nanvar

print("ic_sales\n", ic_sales)
# Get the 50th percentile of the data
np.percentile(ic_sales, 50, axis=0)
# Get 1st column
ic_sales[:,0]

# Correlation coefficient : Measure of correlation between data
# Closer to 1 the more the data is correlated
np.corrcoef(ic_sales[:,0], ic_sales[:,1])

# Calculating Regression line
# Σ(x-x̅)*(y-ȳ) / Σ(x-x̅)2
temp_mean = np.mean(ic_sales[:,0])
sales_mean = np.mean(ic_sales[:,1])
numerator = np.sum(((ic_sales[:,0] - temp_mean)*(ic_sales[:,1] - sales_mean)))
denominator = np.sum(np.square(ic_sales[:,0] - temp_mean))
slope = numerator/denominator
# Calculate y intercept
y_i = sales_mean - slope * temp_mean
y_i
reg_arr = ic_sales[:,0] * slope + y_i
reg_arr

ic_sales
 [[ 37 292]
 [ 40 228]
 [ 49 324]
 [ 61 376]
 [ 72 440]
 [ 79 496]
 [ 83 536]
 [ 81 556]
 [ 75 496]
 [ 64 412]
 [ 53 324]
 [ 40 320]]


array([256.01208459, 273.8864465 , 327.50953224, 399.00697989,
       464.54630691, 506.25315137, 530.08563392, 518.16939265,
       482.42066882, 416.88134181, 351.34201479, 273.8864465 ])

# <a id='TF'>Trigonometric Functions</a>
[Go back to the main page](#main)

In [10]:
# Generate array of 200 values between -pi & pi
t_arr = np.linspace(-np.pi, np.pi, 200)

# Plot with x axis & y axis data 
# plt.plot(t_arr, np.sin(t_arr)) # SIN
# plt.plot(t_arr, np.cos(t_arr)) # COS
# plt.plot(t_arr, np.tan(t_arr)) # TAN
# Display plot
# plt.show()

# Provides inverse of If y = cos(x), x = arccos(y)
np.arcsin(1)
np.arccos(1)
np.arctan(0)

# Also arctan2, sinh, cosh, tanh, arcsinh, arccosh, arctanh

# Radians to degrees
np.rad2deg(np.pi)
# Degrees to radians
np.deg2rad(180)

# Hypotenuse c = √w² + h²
np.hypot(10,10)

14.142135623730951

# <a id='MF'>Matrix Functions</a>
[Go back to the main page](#main)

In [11]:
from numpy import linalg as LA

print("arr_5\n", arr_5)
print("arr_6\n", arr_6)
arr_8 = np.array([[5, 6], [7, 8]])

# Matrix multiplication with Dot Product
# (1 * 2) + (2 * 6) = 14 [0,0]
# (1 * 4) + (2 * 9) = 22 [0,1]
# (3 * 2) + (4 * 6) = 30 [1,0]
# (3 * 4) + (4 * 9) = 12 + 36 = 48 [1,1]
np.dot(arr_5, arr_6)
# Compute dot product of 2 or more arrays
LA.multi_dot([arr_5, arr_6, arr_8])

# Inner product 
# (1 * 2) + (2 * 4) = 10 [0,0]
# (1 * 6) + (2 * 9) = 24 [0,1]
# (3 * 2) + (4 * 4) = 22 [1,0]
# (3 * 6) + (4 * 9) = 54 [1,1]
np.inner(arr_5, arr_6)
np.dot(arr_5, arr_6)

# Tensor Dot Product
# (1 * 1) + (2 * 2) + (3 * 3) + (4 * 4) = 30
# (5 * 1) + (6 * 2) + (7 * 3) + (8 * 4) = 
arr_9 = np.array([[[1, 2],
        [3, 4]],
       [[5, 6],
        [7, 8]]])
arr_10 = np.array([[1, 2],
       [3, 4]], dtype=object)
np.tensordot(arr_9, arr_10)

# Einstein Summation : Provides many ways to perform
# operations on multiple arrays
arr_11 = np.array([0, 1])
arr_12 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# Left Side of -> : 1 axis for arr_11 and 2 axis for arr_12
# Right of -> : Array we want (1D Array)
# ij : Means multiply arr_11 single item by each column of arr_12 and sum
# [0, 4 + 5 + 6 + 7]
np.einsum('i,ij->i', arr_11, arr_12)
# Sum values in arr_11
np.einsum('i->', arr_11)
# Dot Product
print("arr_3\n", arr_3)
print("arr_4\n", arr_4)
np.einsum('i,i->', arr_3, arr_4)
# Matrix multiplication
np.einsum('ij,jk', arr_5, arr_6)
# Get diagonal
np.einsum('ii', arr_5)
# Transpose
np.einsum('ji', arr_5)

# Raise matrix to the power of n
# Given [[a, b], [c, d]]
# [[a² + bc, ab +db], [ac + dc, d² + bc]
LA.matrix_power(arr_5, 2)

# Kronecker product of 2 arrays
# Given [[a, b], [c, d]], [[e, f], [g, h]]
# [[a*e, a*f, b*e, b*f], [a*g, a*h, b*g, b*h], ...]
np.kron(arr_5, arr_6)

# Compute eigenvalues
LA.eig(arr_5) # Returns eigenvectors
LA.eigvals(arr_5)

# Get Vector Norm sqrt(sum(x**2))
LA.norm(arr_5)

# Get Multiplicative Inverse of a matrix
LA.inv(arr_5)

# Get Condition number of matrix
LA.cond(arr_5)

# Determinates are used to compute volume, area, to solve systems
# of equations and more. It is a way you can multiply values in a
# matrix to get 1 number.
# For a matrix to have an inverse its determinate must not equal 0
# det([[a, b], [c, d]]) = a*d - b*c
arr_12 = np.array([[1, 2], [3, 4]])
# 1*4 - 2*3 = -2
LA.det(arr_12)

# Determinate of 3x3 Matrix
# det([[a, b, c], [d, e, f], [g, h, i]]) = a*e*i - b*d*i + c*d*h
# - a*f*h + b*f*g - c*e*g

# When we multiply a matrix times its inverse we get the identity
# matrix [[1,0],[0,1]] for a 2x2 matrix
# Calculate the inverse 1/(a*d - b*c) * [[d, -b], [-c, a]]
# 1/(4 - 6) = -.5 -> [[-.5*4, -.5*-2], [-.5*-3, -.5*a]]
arr_12_i = LA.inv(arr_12)
arr_12_i

np.dot(arr_12, arr_12_i)

# Solving Systems of Linear Equations
# If you have 3x + 5 = 9x -> 5 = 6x -> x = 5/6
# If you have x + 4y = 10 & 6x + 18y = 42
# Isolate x -> x = 10 - 4y
# 6(10 - 4y) + 18y = 42 -> 60 - 24y + 18y = 42 - > -6y = -18 -> y = 3
# x + 4*3 = 10 -> x = -2
arr_13 = np.array([[1, 4], [6, 18]])
arr_14 = np.array([10, 42])
# Solve will solve this for you as well
LA.solve(arr_13, arr_14)

# Return a identity matrix with defined number of rows and columns
np.eye(2, 2, dtype=int)

arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]
arr_3
 [1 2 3 4]
arr_4
 [2 4 6 8]


array([[1, 0],
       [0, 1]])

# <a id='S&LNO'>Saving & Loading NumPy Objects</a>
[Go back to the main page](#main)

In [12]:
arr_15 = np.array([[1, 2], [3, 4]])
# Save as randarray.npy
np.save('randarray', arr_15)
# Load saved array 
arr_16 = np.load('randarray.npy')
arr_16

# Save as a CSV 
np.savetxt('randcsv.csv', arr_15)
# Load CSV
arr_17 = np.loadtxt('randcsv.csv')
arr_17

array([[1., 2.],
       [3., 4.]])

# <a id='FF'>Financial Functions</a>
[Go back to the main page](#main)

In [13]:
pip install numpy-financial

Note: you may need to restart the kernel to use updated packages.


In [14]:
# pip install numpy-financial
import numpy_financial as npf

# Compute future value of $400 investment every month
# with an annual rate of 8% after 10 years
npf.fv(.08/12, 10*12, -400, -400)

# Calculate interest portion of payment on a loan of $3,000
# at 9.25% per year compounded monthly
# Period of loan (year)
period = np.arange(1*12) + 1
principle = 3000.00
# Interest Payment
ipmt = npf.ipmt(0.0925/12, period, 1*12, principle)
# Principle Payment
ppmt = npf.ppmt(0.0925/12, period, 1*12, principle)
for payment in period:
    index = payment - 1
    principle = principle + ppmt[index]
    print(f"{payment}   {np.round(ppmt[index], 2)}    {np.round(ipmt[index],2)}    {np.round(principle, 2)}")

# Compute number of payments to pay off $3,000 if you paid
# $150 per month with an interest rate of 9.25%
np.round(npf.nper(0.0925/12, -150, 3000.00), 2)

# Calculate net present value of cash flows of $4,000, $5,000
# $6,000, $7,000 after $15,000 investment with .08 rate per period
npf.npv(0.08, [-15000, 4000, 5000, 6000, 7000]).round(2)

1   -239.58    -23.12    2760.42
2   -241.42    -21.28    2519.0
3   -243.29    -19.42    2275.71
4   -245.16    -17.54    2030.55
5   -247.05    -15.65    1783.5
6   -248.95    -13.75    1534.55
7   -250.87    -11.83    1283.67
8   -252.81    -9.89    1030.87
9   -254.76    -7.95    776.11
10   -256.72    -5.98    519.39
11   -258.7    -4.0    260.69
12   -260.69    -2.01    0.0


2898.6

# <a id='CF'>Comparison Functions</a>
[Go back to the main page](#main)

In [15]:
carr_1 = np.array([2, 3])
carr_2 = np.array([3, 2])
# Returns boolean based on whether arr_1 value Comparison arr_2 value
np.greater(carr_1, carr_2)
np.greater_equal(carr_1, carr_2)
np.less(carr_1, carr_2)
np.less_equal(carr_1, carr_2)
np.not_equal(carr_1, carr_2)
np.equal(carr_1, carr_2)

array([False, False])