<div style="border:2px solid #174D83; border-radius:15px;  background:#ffffff;">
    <div style="padding:10px 10px 10px 0px; margin:5px; border-radius:12px; background:#174D83; text-align:center;">
        <span style="font-family:sans-serif; font-size:42px; color:#fff;">Comprehensive NumPy tutorial with examples 📚</span>
    </div>
</div>

<div style="border:2px solid #174D83; border-radius:10px;  background:#fff;">
    <div style="padding:10px 10px 10px 0px; margin:2px; border-radius:10px; background:#174D83;">
        <span style="margin-left:15px; font-family:sans-serif; font-size:20px; color:#fff;">Introduction...</span>
    </div>
</div>

<div style="border:1px solid blue; border-radius:10px; padding:2px">
    <img src="https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png" width="100%">
</div>
<div style="padding:4px">
    
    
    
### <span style='background:yellow;color:#000000;'>What is Numpy?</span>


* <span style='background:#174D83;color:#fff;'><b>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. The ancestor of NumPy, Numeric, was originally created by Jim Hugunin with contributions from several other developers. In 2005, Travis Oliphant created Numpy by incorporating features of the competing Numarray into Numeric, with extensive modifications. Numpy is open-source software and has many contributors. Numpy is a NumFOCUS fiscally sponsored project.</b></span>

### <span style='background:yellow;color:#000000;'>History of Numpy?</span>

    
* <span style='background:#174D83;color:#fff;'><b>The Python programming language was not originally designed for numerical computing, but attracted the attention of the scientific and engineering community early on. In 1995 the special interest group (SIG) matrix-sig was founded with the aim of defining an array computing package; among its members was Python designer and maintainer Guido van Rossum, who extended Python's syntax (in particular the indexing syntax) to make array computing easier. An implementation of a matrix package was completed by Jim Fulton, then generalized by Jim Hugunin and called Numeric (also variously known as the "Numerical Python extensions" or "NumPy"). Hugunin, a graduate student at the Massachusetts Institute of Technology (MIT), joined the Corporation for National Research Initiatives (CNRI) in 1997 to work on JPython, leaving Paul Dubois of Lawrence Livermore National Laboratory (LLNL) to take over as maintainer. Other early contributors include David Ascher, Konrad Hinsen and Travis Oliphant. A new package called Numarray was written as a more flexible replacement for Numeric. Like Numeric, it too is now deprecated. Numarray had faster operations for large arrays, but was slower than Numeric on small ones, so for a time both packages were used in parallel for different use cases. The last version of Numeric (v24.2) was released on 11 November 2005, while the last version of numarray (v1.5.2) was released on 24 August 2006. There was a desire to get Numeric into the Python standard library, but Guido van Rossum decided that the code was not maintainable in its state then. In early 2005, NumPy developer Travis Oliphant wanted to unify the community around a single array package and ported Numarray's features to Numeric, releasing the result as NumPy 1.0 in 2006. This new project was part of SciPy. To avoid installing the large SciPy package just to get an array object, this new package was separated and called NumPy. Support for Python 3 was added in 2011 with NumPy version 1.5.0. In 2011, PyPy started development on an implementation of the NumPy API for PyPy. It is not yet fully compatible with NumPy.</b></span>



### <span style='background:yellow;color:#000000;'>Features of numpy</span>

    
* <span style='background:#174D83;color:#ffffff;'><b>Numpy targets the CPython reference implementation of Python, which is a non-optimizing bytecode interpreter. Mathematical algorithms written for this version of Python often run much slower than compiled equivalents due to the absence of compiler optimization. Numpy addresses the slowness problem partly by providing multidimensional arrays and functions and operators that operate efficiently on arrays; using these requires rewriting some code, mostly inner loops, using NumPy. Using NumPy in Python gives functionality comparable to MATLAB since they are both interpreted, and they both allow the user to write fast programs as long as most operations work on arrays or matrices instead of scalars. In comparison, MATLAB boasts a large number of additional toolboxes, notably Simulink, whereas NumPy is intrinsically integrated with Python, a more modern and complete programming language. Moreover, complementary Python packages are available; SciPy is a library that adds more MATLAB-like functionality and Matplotlib is a plotting package that provides MATLAB-like plotting functionality. Internally, both MATLAB and NumPy rely on BLAS and LAPACK for efficient linear algebra computations. Python bindings of the widely used computer vision library OpenCV utilize NumPy arrays to store and operate on data. Since images with multiple channels are simply represented as three-dimensional arrays, indexing, slicing or masking with other arrays are very efficient ways to access specific pixels of an image. The NumPy array as universal data structure in OpenCV for images, extracted feature points, filter kernels and many more vastly simplifies the programming workflow and debugging.</b></span>


#### <span style="color:#CF350C">REFERENCE:</span> https://en.wikipedia.org/wiki/NumPy

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;"> 1. Install and import numpy library...</span>

In [1]:
#!pip install numpy
import numpy as np

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">2. Check numpy version...</span>

In [2]:
np.__version__

'1.24.3'

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">3. Create numpy arrays...</span>

In [3]:
arr = np.array([1,2,3,4,5, 6, 8, 11])
print("Numpy array: ", arr, "\n")
print("Type: ", type(arr))

Numpy array:  [ 1  2  3  4  5  6  8 11] 

Type:  <class 'numpy.ndarray'>


In [4]:
np.arange(0, 25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
np.arange(0, 25, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

### <mark>Create an empyt array</mark>

In [6]:
empty_arr = np.empty([5, 5], int)

print(empty_arr)

[[-1839181712         423 -1839181712         423 -1839181712]
 [        423         257           0  1801678592  1412265061]
 [    6647929         423           0           0          15]
 [          0  1279345920       21061           0           0]
 [          0           0          15           0           0]]


### <mark>Check elements count</mark>

In [7]:
arr1 = np.array([])
arr2 = np.array([1, 2])

def elements(array):
    return array.ndim and array.size
        
print(arr1, "elements_count:", elements(arr1))
print(arr2, "elements_count:", elements(arr2))

[] elements_count: 0
[1 2] elements_count: 2


### <mark>Check whether the array is empty</mark>

In [8]:
a = np.array([])
b = np.array([1, 2])

def if_empty(a):
    if a.size == 0:
        print(a, "is empty array")
    else:
        print(b, "is not empty array")
        
if_empty(a)
if_empty(b)

[] is empty array
[1 2] is not empty array


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">4. Numpy arrays are fixed data type</span>

### <mark>That is, if there is one decimal number in it, it converts the others to decimal</mark>

In [9]:
arr = np.array([1, 2, 3, 4, 5, 2.5])
arr

array([1. , 2. , 3. , 4. , 5. , 2.5])

In [10]:
arr = np.array([1,2,3,4,5, 5.2, 1.2], dtype = "float32")
arr

array([1. , 2. , 3. , 4. , 5. , 5.2, 1.2], dtype=float32)

In [11]:
arr = np.array([1, 2, 3, 4, 5, 5.2, 1.2], dtype = "int")
arr

array([1, 2, 3, 4, 5, 5, 1])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">5. Create arrays without using lists</span>

### <mark>Create an array of zeros</mark>

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros(5, dtype = "int")

array([0, 0, 0, 0, 0])

### <mark>Create an array of ones</mark>

In [15]:
np.ones(7, dtype = "int")

array([1, 1, 1, 1, 1, 1, 1])

In [16]:
np.ones((4, 7), dtype = "float32")

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

### <mark>Create an array of sevens</mark>

In [17]:
np.full((3, 4), 7, dtype = "float32")

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]], dtype=float32)

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">6. Linspace function</span>

### <mark>Return evenly spaced numbers over a specified interval</mark>

In [18]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.linspace(1, 10, 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [20]:
np.linspace(2, 9, 15)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. ])

In [21]:
np.linspace(1, 10, 15, dtype = int)

array([ 1,  1,  2,  2,  3,  4,  4,  5,  6,  6,  7,  8,  8,  9, 10])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">7. Random function</span>

In [22]:
arr = np.random.normal(10, 7, (3, 4))
arr

array([[ 7.70364677,  3.63754133, 10.81778424, 15.77391053],
       [17.5347672 , -3.65219914,  8.11697939, 23.98005014],
       [ 1.45228056,  5.6361414 , 17.73768298,  5.25818335]])

In [23]:
np.random.randint(0, 12, (3,5))

array([[ 1, 10,  7,  6,  1],
       [ 6,  5,  1,  0, 10],
       [ 0,  2,  2,  5,  7]])

In [24]:
np.random.randint(1, 9, 10)

array([6, 3, 1, 7, 6, 8, 3, 6, 8, 1])

In [25]:
np.random.randint(1, 25, (5,5))

array([[22,  3,  6, 10, 24],
       [ 6,  8,  5,  3, 24],
       [ 3, 21, 13, 19,  5],
       [22, 14, 17,  4,  2],
       [21,  4, 19, 23, 15]])

In [26]:
np.random.randint(10, size = (2))

array([9, 9])

In [27]:
a = np.random.randint(10, size = (2, 3))

print(a, "\n")
print(a, ".shape:", a.shape, "\n")
print("datatype:", a.dtype)

[[0 2 7]
 [5 6 0]] 

[[0 2 7]
 [5 6 0]] .shape: (2, 3) 

datatype: int32


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">8. ndim, shape, size, dtype functions</span>

* ### <mark>ndim - size number</mark>
* ### <mark>shape - shape info</mark>
* ### <mark>size - total element number</mark>
* ### <mark>dtype - data type of elements of array</mark>

In [28]:
arr = np.random.randint(10, size = 7)
print("Array:", arr)

Array: [7 4 4 9 3 4 1]


In [29]:
for i in (arr.shape, arr.dtype, arr.ndim,arr.size):
    print(i)

(7,)
int32
1
7


In [30]:
arr_1 = np.random.randint(10, size = (5, 7))
print("Array:\n\n", arr_1)

Array:

 [[3 7 6 9 4 9 0]
 [1 1 4 4 6 8 0]
 [9 6 4 2 9 0 4]
 [1 2 3 9 7 4 3]
 [7 7 7 4 0 8 4]]


In [31]:
for i in (arr_1.shape, arr_1.dtype, arr_1.ndim, arr_1.size):
    print(i)

(5, 7)
int32
2
35


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">9. Reshape function</span>

In [32]:
arr = np.arange(0, 15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [33]:
arr = arr.reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### <mark>Here we create a matrix keeping the vector format</mark>

In [34]:
arr = np.arange(1, 15)

arr = arr.reshape((1, 14))
for i in (arr, "***********", arr.ndim):
    print(i)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
***********
2


### <mark>Reshape with -1</mark>

In [35]:
arr = np.matrix([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("Original numpy array and its shape :")
print(arr, "\n\n", arr.shape)

Original numpy array and its shape :
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

 (3, 5)


In [36]:
c = np.reshape(arr, -1)
print("\nreshaping the array like (arr, -1):")
print(c)
print("\nnew shape:", c.shape)


reshaping the array like (arr, -1):
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]

new shape: (1, 15)


In [37]:
d = np.reshape(arr, (1, -1))
print("reshaping array like (arr, (1, -1)):")
print(d)
print("\nnew shape: ", d.shape)

reshaping array like (arr, (1, -1)):
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]

new shape:  (1, 15)


In [38]:
e = np.reshape(arr, (3, -1))
print("reshaping the array - (arr, (3, -1)):")
print(e)
print("\nnew shape:", e.shape)

reshaping the array - (arr, (3, -1)):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

new shape: (3, 5)


In [39]:
f = np.reshape(arr, (3, -1))
print("reshaping the array - (arr, (3, -1)):")
print(f)
print("\nnew shape:", f.shape)

reshaping the array - (arr, (3, -1)):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

new shape: (3, 5)


In [40]:
g = np.reshape(arr, (5, -1))
print("reshaping the array - (a, (4, -1)):")
print(g)
print("\nnew shape:", g.shape)

reshaping the array - (a, (4, -1)):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

new shape: (5, 3)


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">10. Concatenate arrays</span>

### <mark>One dimensional arrays</mark>

In [41]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([5,6,7])
np.concatenate([arr_1, arr_2, arr_3])

array([1, 2, 3, 4, 5, 6, 5, 6, 7])

### <mark>Two dimensional arrays</mark>

In [42]:
arr_1 = np.array([[1,2,3,4],
               [5,6,7,8]])

arr_2 = np.array([[9,10,11,12],
               [13,14,15,16]])

np.concatenate([arr_1, arr_2], axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
np.concatenate([arr_1,arr_2], axis = 1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">11. Array splitting</span>

In [44]:
arr = np.array([1,2,3,22,22,4,5,6])
np.split(arr, [3, 5])

[array([1, 2, 3]), array([22, 22]), array([4, 5, 6])]

In [45]:
a, b, c = np.split(arr, [3, 5])
for i in (a, b, c):
    print(i)

[1 2 3]
[22 22]
[4 5 6]


### <mark>Split two dimensional arrays</mark>

In [46]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
top, bottom = np.vsplit(arr, [2])
top, bottom

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [48]:
left, right = np.hsplit(arr, [2])
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">12. Sort the arrays</span>

In [49]:
arr = np.array([2, 6, 1, 4, 7, 3, 9, 1, 0, 11])
print(np.sort(arr))

[ 0  1  1  2  3  4  6  7  9 11]


In [50]:
arr = np.array([2,6,1,4,7,3,9,1,0,11])
arr.sort()
arr

array([ 0,  1,  1,  2,  3,  4,  6,  7,  9, 11])

### <mark>Sorting two dimensional arrays</mark>

In [51]:
arr_1 = np.random.randint(1, 16, (3, 5))
arr_1

array([[15,  7,  3, 15,  1],
       [15,  7,  9,  8, 11],
       [ 2, 11, 10, 13,  4]])

In [52]:
np.sort(arr_1, axis = 1)

array([[ 1,  3,  7, 15, 15],
       [ 7,  8,  9, 11, 15],
       [ 2,  4, 10, 11, 13]])

In [53]:
np.sort(arr_1, axis = 0)

array([[ 2,  7,  3,  8,  1],
       [15,  7,  9, 13,  4],
       [15, 11, 10, 15, 11]])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">13. Acces array elements by index</span>

In [54]:
arr = np.array([1, 3, 4, 6, 2, 7, 9, 4, 6, 2, 0])

In [55]:
arr[0]

1

In [56]:
 arr[-2]

2

In [57]:
arr[:]

array([1, 3, 4, 6, 2, 7, 9, 4, 6, 2, 0])

In [58]:
arr[:-2]

array([1, 3, 4, 6, 2, 7, 9, 4, 6])

In [59]:
arr[3:5]

array([6, 2])

In [60]:
arr[::-1]

array([0, 2, 6, 4, 9, 7, 2, 6, 4, 3, 1])

In [61]:
arr_1 = np.array([[2,5,7,9,0,1,3],
                 [1,5,7,5,9,12,14],
                 [15,13,18,34,14,19,21]])
arr_1

array([[ 2,  5,  7,  9,  0,  1,  3],
       [ 1,  5,  7,  5,  9, 12, 14],
       [15, 13, 18, 34, 14, 19, 21]])

In [62]:
arr_1[0, 0]

2

### <mark>Get 7 in the second row and the second column</mark>

In [63]:
arr_1[1, 2]

7

### <mark>Get 21 value</mark>

In [64]:
arr_1[2,-1]

21

### <mark>Change a value</mark>

In [65]:
arr_1[2, -2] = 111
arr_1

array([[  2,   5,   7,   9,   0,   1,   3],
       [  1,   5,   7,   5,   9,  12,  14],
       [ 15,  13,  18,  34,  14, 111,  21]])

In [66]:
# Here we insert a float value from the outside into the array of integer values.
# In this case, because the arrays are of fixed type, the decimal part will be discarded.
arr_1[0,-1] = 55.5
arr_1

array([[  2,   5,   7,   9,   0,   1,  55],
       [  1,   5,   7,   5,   9,  12,  14],
       [ 15,  13,  18,  34,  14, 111,  21]])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">14. Array slicing</span>

In [67]:
arr = np.arange(10, 25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
arr[0:5]

array([10, 11, 12, 13, 14])

In [69]:
arr[:5]

array([10, 11, 12, 13, 14])

In [70]:
arr[3:]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
arr[::2]

array([10, 12, 14, 16, 18, 20, 22, 24])

In [72]:
arr[1::2]

array([11, 13, 15, 17, 19, 21, 23])

In [73]:
arr[::3]

array([10, 13, 16, 19, 22])

### <mark>Slicing two dimensional arrays</mark>

In [74]:
arr1 = np.arange(0, 25).reshape(5, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
arr1[:, :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
arr1[:, 1]

array([ 1,  6, 11, 16, 21])

In [77]:
arr1[:, 4]

array([ 4,  9, 14, 19, 24])

In [78]:
arr1[:, -1]

array([ 4,  9, 14, 19, 24])

In [79]:
arr1[2:, 2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [80]:
arr1[0, :]

array([0, 1, 2, 3, 4])

In [81]:
arr1[1, :]

array([5, 6, 7, 8, 9])

In [82]:
arr1[4, 4]

24

In [83]:
arr1[-1,-1]

24

In [84]:
arr1[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [85]:
arr1[1:3, 0:2]

array([[ 5,  6],
       [10, 11]])

In [86]:
a = np.arange(15).reshape(3, 5)
print("Before slice:")
print(a)

print("\nAfter slice:")
b = a[::-1, ::-1]
print(b)

Before slice:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

After slice:
[[14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">15. Copy function</span>

#### <mark>copy() function is used so that operations performed on subsets do not affect the main set</mark>

In [87]:
arr = np.random.randint(10, size = (5, 5))
arr

array([[1, 3, 2, 3, 0],
       [2, 0, 1, 6, 7],
       [9, 2, 4, 8, 2],
       [0, 2, 3, 8, 2],
       [8, 7, 3, 5, 2]])

In [88]:
subset = arr[0:2, 0:3]
subset

array([[1, 3, 2],
       [2, 0, 1]])

In [89]:
subset[1, 1] = 333
subset[1, 2] = 444
subset

array([[  1,   3,   2],
       [  2, 333, 444]])

In [90]:
arr

array([[  1,   3,   2,   3,   0],
       [  2, 333, 444,   6,   7],
       [  9,   2,   4,   8,   2],
       [  0,   2,   3,   8,   2],
       [  8,   7,   3,   5,   2]])

In [91]:
arr1 = np.random.randint(1, 15, (3, 5))
arr1

array([[13,  1,  6, 10,  6],
       [ 1, 14, 14,  9,  7],
       [ 6, 12,  7,  7, 11]])

In [92]:
arr2 = arr1.copy()
subset_b = arr2[:, 2]
subset_b

array([ 6, 14,  7])

In [93]:
subset_b[1] = 777
subset_b

array([  6, 777,   7])

In [94]:
arr2

array([[ 13,   1,   6,  10,   6],
       [  1,  14, 777,   9,   7],
       [  6,  12,   7,   7,  11]])

In [95]:
arr1

array([[13,  1,  6, 10,  6],
       [ 1, 14, 14,  9,  7],
       [ 6, 12,  7,  7, 11]])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">16. Fancy index</span>

In [96]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [97]:
fancy_index = [1, 3, 5]
arr[fancy_index]

array([ 3,  9, 15])

#### <mark>Fancy indexing on two dimensional arrays</mark>

In [98]:
arr = np.arange(9)
arr = arr.reshape(3, 3)
row = np.array([0, 1])
column = np.array([1, 2])
arr[row, column]

array([1, 5])

In [99]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
arr[0, [1, 2]]

array([1, 2])

In [101]:
#slice

arr[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [102]:
arr[1, [0,1]]

array([3, 4])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">17. Conditional element operations</span>

In [103]:
arr = np.array([1, 2, 3, 4, 5])
arr > 3

array([False, False, False,  True,  True])

In [104]:
arr[arr > 3]

array([4, 5])

In [105]:
arr[arr < 5]

array([1, 2, 3, 4])

In [106]:
arr[arr >= 2]

array([2, 3, 4, 5])

In [107]:
arr[arr != 4]

array([1, 2, 3, 5])

In [108]:
arr[arr == 3]

array([3])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">18. Mathematical operations on arrays</span>

In [109]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
(arr*2)+5

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [111]:
np.sqrt(((arr*2)+5))

array([2.23606798, 2.64575131, 3.        , 3.31662479, 3.60555128,
       3.87298335, 4.12310563, 4.35889894, 4.58257569, 4.79583152])

In [112]:
0.9**((arr*2)+5)

array([0.59049   , 0.4782969 , 0.38742049, 0.3138106 , 0.25418658,
       0.20589113, 0.16677182, 0.13508517, 0.10941899, 0.08862938])

In [113]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [114]:
for i in (arr - 1, arr*5, arr/3):
    print(i)

[0 1 2 3 4]
[ 5 10 15 20 25]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [115]:
arr*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [116]:
np.subtract(arr, 2)

array([-1,  0,  1,  2,  3])

In [117]:
np.add(arr, 3)

array([4, 5, 6, 7, 8])

In [118]:
np.divide(arr, 4)

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [119]:
np.multiply(arr, 5)

array([ 5, 10, 15, 20, 25])

In [120]:
np.power(arr, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [121]:
np.mod(arr, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [122]:
np.absolute(arr)

array([1, 2, 3, 4, 5])

In [123]:
np.sin(90)

0.8939966636005579

In [124]:
np.cos(122)

-0.8667670910519801

In [125]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [126]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [127]:
np.arctan(arr)

array([0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">19. Solving two unknown equations with numpy</span>


#### <mark>5*x0+x1 = 12</mark>
#### <mark>x0+3*x1 = 10</mark>

In [128]:
arr1 = np.array([[5,1], [1,3]])
arr2 = np.array([12,10])
x = np.linalg.solve(arr1, arr2)
x

array([1.85714286, 2.71428571])

##### 2*x0 - 3*x1 = 5
##### x0 + 2*x1 = 6

In [129]:
arr3 = np.array([[2,3], [1,2]])
arr4 = np.array([5,6])
x = np.linalg.solve(arr3, arr4)
x

array([-8.,  7.])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">20. Additional information about arrays</span>

In [130]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

#### <mark>Create five random values between 0 and 1</mark>

In [131]:
np.random.rand(5)

array([0.47002824, 0.45381049, 0.49328844, 0.85968456, 0.61807621])

#### <mark>Create five random values around 0</mark>

In [132]:
np.random.randn(5)

array([ 0.45408442, -0.33859487, -0.18710806,  2.13268187, -0.24004517])

In [133]:
arr = np.random.randint(1, 50, 50)
arr

array([17, 10,  5, 48,  5, 42, 31, 43,  7, 21, 23, 19, 14, 44,  4, 10, 17,
       49, 23, 14, 33,  5, 30,  6, 39,  5, 15, 43, 21, 32, 19, 37, 29,  3,
       41,  3,  3, 15, 38,  6, 17, 13, 11,  9, 29, 32, 26, 25, 24,  1])

#### <mark>Get the index where the maximum value is</mark>

In [134]:
np.argmax(arr)

17

#### <mark>Get the index where the minimum value is</mark>

In [135]:
np.argmin(arr)

49

In [136]:
np.sum(arr)

1056

In [137]:
np.mean(arr)

21.12

In [138]:
np.median(arr)

19.0

In [139]:
np.var(arr)

191.5856

In [140]:
np.std(arr)

13.841445011269597

### <mark>Adding the arrays</mark>

In [141]:
arr1 = np.array([[1,2,3,4,5], [2,3,5,6,7]])
arr2 = np.array([[1.1,2.1,3.1,4.1,5.1], [2.1,3.1,5.1,6.1,7.1]])
arr1 + arr2

array([[ 2.1,  4.1,  6.1,  8.1, 10.1],
       [ 4.1,  6.1, 10.1, 12.1, 14.1]])

### <mark>Multiplying the arrays</mark>

In [142]:
arr1 * arr2

array([[ 1.1,  4.2,  9.3, 16.4, 25.5],
       [ 4.2,  9.3, 25.5, 36.6, 49.7]])

In [143]:
np.sqrt(arr1 + arr2)

array([[1.44913767, 2.02484567, 2.46981781, 2.84604989, 3.17804972],
       [2.02484567, 2.46981781, 3.17804972, 3.47850543, 3.75499667]])

### <mark>Multiplying the elements of two lists by traditional methods</mark>

In [144]:
list_1 = [2,4,6,8, 10, 12, 14]
list_2 = [1,3,5,7, 9, 11, 13]

multiplied_lists = []
for i in range(0, len(list_1)):
    multiplied_lists.append(list_1[i] * list_2[i])
multiplied_lists

[2, 12, 30, 56, 90, 132, 182]

### <mark>Multiplying the elements of two lists by NumPy</mark>

In [145]:
arr_1 = np.array([2,4,6,8, 10, 12, 14])
arr_2 = np.array([1,3,5,7, 9, 11, 13])
arr_1 * arr_2

array([  2,  12,  30,  56,  90, 132, 182])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">21. Save array to CSV</span>

In [146]:
a = np.asarray([ [1,2,3], [4,5,6]])
print(a)

# to save the numpy to csv file
# np.savetxt("abc.csv", a, delimiter = ",")

[[1 2 3]
 [4 5 6]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">22. Dataframe to numpy</span>

In [147]:
import pandas as pd

df = pd.DataFrame({"a": [1, 2, 3, 4, 5], "b": [4, 5, 6, 7, 8]}, index = ["X", "Y", "Z", "W", "R"])

print("Pandas dataframe:")
print(df)

Pandas dataframe:
   a  b
X  1  4
Y  2  5
Z  3  6
W  4  7
R  5  8


In [148]:
dat = df.to_numpy()

print("Pandas dataframe to numpy:")
print(dat)

Pandas dataframe to numpy:
[[1 4]
 [2 5]
 [3 6]
 [4 7]
 [5 8]]


In [149]:
idx = df.index.to_numpy()
print("Pandas dataframe indices to numpy:")
print(idx)

Pandas dataframe indices to numpy:
['X' 'Y' 'Z' 'W' 'R']


In [150]:
ser = df["a"].to_numpy()
print("Dataframe series to numpy:")
print(ser)

Dataframe series to numpy:
[1 2 3 4 5]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">23. Argsort on numpy array</span>

In [151]:
a = np.random.randint(0, 10, (3,3))
print("Before argsort:")
print(a)

print("\nAfter argsort:")
b = a[a[: ,2].argsort()]
print(b)

Before argsort:
[[2 6 9]
 [2 7 1]
 [4 7 5]]

After argsort:
[[2 7 1]
 [4 7 5]
 [2 6 9]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">24. Numpy inverse</span>

In [152]:
b = np.array([[2, 3, 5],[4, 6, 8], [9, 11, 15]])
print("Array before inverse:")
print(b)

c = np.linalg.inv(b)
print("\nArray after inverse:")
print(c)

Array before inverse:
[[ 2  3  5]
 [ 4  6  8]
 [ 9 11 15]]

Array after inverse:
[[-0.2 -1.   0.6]
 [-1.2  1.5 -0.4]
 [ 1.  -0.5  0. ]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">25. Tolist function</span>

In [153]:
arr = np.arange(20).reshape(4, 5)
print("Array before:")
print(arr)
print(type(arr))
print(type(arr[1]))
print(type(arr[1][1]))
print("______________________________________________________________________________")

Array before:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int32'>
______________________________________________________________________________


In [154]:
print("Array after tolist():")
b = arr.tolist()
print(b)
print(type(b))
print(type(b[1]))
print(type(b[1][1]))

Array after tolist():
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]
<class 'list'>
<class 'list'>
<class 'int'>


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">26. Where function</span>

In [155]:
arr = np.arange(20).reshape((5, 4))
print("Without using where function:")
print(arr)

print("\nWith using where function:")
b = np.where((a < 16) & (a > 8), 0, 20)
print(b)

Without using where function:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

With using where function:
[[20 20  0]
 [20 20 20]
 [20 20 20]]


In [156]:
arr = np.arange(20).reshape((4, 5))
print("Without using where function:")
print(arr)

print("\nWith using where function:")
b = np.where((a > 4) & (a < 9), 0, a)
print(b)

Without using where function:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

With using where function:
[[2 0 9]
 [2 0 1]
 [4 0 0]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">27. Date with numpy</span>

In [157]:
today = np.datetime64("today", "D")
print("Date of today is: ", today)

Date of today is:  2024-02-21


In [158]:
fivedayslater = np.datetime64("today", "D") + np.timedelta64(5, "D")
print("Date after five days is: ", fivedayslater)

Date after five days is:  2024-02-26


In [159]:
beforetendays = np.datetime64("today", "D") - np.timedelta64(10, "D")
print("Date before ten days is: ", beforetendays)

Date before ten days is:  2024-02-11


In [160]:
afterfiveweek = np.datetime64("today", "D") + np.timedelta64(5, "W")
print("Date after five weeksis: ", afterfiveweek)

Date after five weeksis:  2024-03-27


In [161]:
date_arr = np.arange("2022-08-27", "2022-09-05", dtype = "datetime64[D]")
print("Date between two date:", date_arr)

Date between two date: ['2022-08-27' '2022-08-28' '2022-08-29' '2022-08-30' '2022-08-31'
 '2022-09-01' '2022-09-02' '2022-09-03' '2022-09-04']


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">27. To Find the nearest element in the numpy array</span>

In [162]:
arr = np.arange(10, 50, 2)
print(arr)

b = 15
c = arr.flat[np.abs(arr - b).argmin()]
print(f"Elemenet near by {b} : {c}")

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
Elemenet near by 15 : 14


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">28. Swap array rows</span>

In [163]:
arr = np.arange(25).reshape(5, 5)
print("Array before swapping:")
print(arr)

arr[[0,1]] = arr[[1, 0]]
print("______________________")

print("Array after swapping:")
print(arr)

Array before swapping:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
______________________
Array after swapping:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">29. Shuffle array elements</span>

In [164]:
arr = np.arange(15)
print("Array before shuffling:")
print(arr)

np.random.shuffle(arr)
print("______________________________________________")

print("Array after shuffling:")
print(arr)

Array before shuffling:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
______________________________________________
Array after shuffling:
[ 1  8  6 13 10  4  2  0 12  3  5  7 14 11  9]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">30. Median function</span>

In [165]:
arr = np.arange(20).reshape((4, 5))
print(arr)

print("\nMedian of the array is: ", np.median(arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Median of the array is:  9.5


# Thank you all 😊